// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"demo/domain/useCases"
	"demo/infra/dataStore"
)

// Injectors from wire.go:

func CreateApp() *Application {
	databaseGateway := dataStore.NewMongoGatewayImpl()
	userUseCase := useCases.NewUserUseCase(databaseGateway)
	application := NewApplication(databaseGateway, userUseCase)
	return application
}
